services:
  mysql-db:
    image: mysql:latest
    # docker pull mysql:oracle
    container_name: mysql-db
    volumes:
      - moodle_db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME} 
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_unicode_ci
  redis:
    image: redis:alpine
    container_name: moodle-redis
    environment:
      - TZ=America/Sao_Paulo
    restart: always

  moodle-cli:
    image: ruseler/moodle-php-cli:latest
    container_name: moodle-cli
    env_file:
      - ./.env
    volumes:
      - moodle_data:${MDLHOME}
      - ./scripts:/scripts:ro
    entrypoint: [ "/bin/sh", "/scripts/init-plugins-release.sh" ]
  moodle:
    image: ruseler/moodle-php-apache:latest
    container_name: moodle-app
    depends_on:
      moodle-cli:
        condition: service_completed_successfully
      mysql-db:
        condition: service_started
    ports:
      - "${HOST_PORT}:80"
    environment:
      - MOODLE_DB_TYPE=${DB_TYPE}
      - MOODLE_DB_HOST=${DB_HOST}
      - MOODLE_DB_NAME=${DB_NAME}
      - MOODLE_DB_USER=${DB_USER}
      - MOODLE_DB_PASSWORD=${DB_PASS}
      - MOODLE_URL=${MOODLE_URL}
      - MOODLE_REDIS_HOST=redis
      - APACHE_DOCUMENT_ROOT=${APACHE_DOC}
    volumes:
      - moodle_data:${MDLHOME}
      - moodledata_private:/var/www/moodledata

  moodle-cron:
    image: ruseler/moodle-php-cli:latest
    container_name: moodle-cron
    depends_on:
      - mysql-db
      - moodle
    volumes:
      - moodle_data:${MDLHOME}
      - moodledata_private:/var/www/moodledata
    # This runs the Moodle cron script every 60 seconds
    entrypoint: /bin/sh -c "while true; do php ${MDLHOME}/admin/cli/cron.php > /proc/1/fd/1 2>/proc/1/fd/2; sleep 60; done"
    restart: always
  phpmyadmin:
    image: linuxserver/phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=3306
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    depends_on:
      - mysql-db
volumes:
  moodle_db_data:
  moodle_data:
  moodledata_private:
