services:
  moodle-db:
    image: postgres:alpine
    container_name: moodle-db
    volumes:
      - moodle_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  redis:
    image: redis:alpine
    container_name: moodle-redis
    restart: always

  moodle-cli:
    image: ruseler/moodle-php-cli:latest
    container_name: moodle-cli
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - MOODLE_URL=${MOODLE_URL}
      - MDLREPO=${MDLREPO}
      - MDLBRANCH=${MDLBRANCH}
      - PLGSREPO=${PLGSREPO}
      - PLGBRANCH=${PLGBRANCH}
      - MDLHOME=${MDLHOME}
      - APACHE_DOC=${APACHE_DOC}
    volumes:
      - moodle_data:${MDLHOME}
      - ./scripts:/scripts:ro
    entrypoint: [ "/bin/sh", "/scripts/init-plugins-release.sh" ]
  moodle:
    image: ruseler/moodle-php-apache:latest
    container_name: moodle-app
    depends_on:
      moodle-cli:
        condition: service_completed_successfully
      moodle-db:
        condition: service_started
    ports:
      - "${HOST_PORT}:80"
    environment:
      - MOODLE_DB_TYPE=pgsql
      - MOODLE_DB_TYPE=pgsql
      - MOODLE_DB_HOST=moodle-db
      - MOODLE_DB_NAME=${DB_NAME}
      - MOODLE_DB_USER=${DB_USER}
      - MOODLE_DB_PASSWORD=${DB_PASS}
      - MOODLE_URL=${MOODLE_URL}
      - MOODLE_REDIS_HOST=redis
      - APACHE_DOCUMENT_ROOT=${APACHE_DOC}
    volumes:
      - moodle_data:${MDLHOME}
      - moodledata_private:/var/www/moodledata

  moodle-cron:
    image: ruseler/moodle-php-cli:latest
    container_name: moodle-cron
    depends_on:
      - moodle-db
      - moodle
    volumes:
      - moodle_data:${MDLHOME}
      - moodledata_private:/var/www/moodledata
    # This runs the Moodle cron script every 60 seconds
    entrypoint: /bin/sh -c "while true; do php ${MDLHOME}/admin/cli/cron.php; sleep 60; done"
    restart: always

volumes:
  moodle_db_data:
  moodle_data:
  moodledata_private:
